apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-basic
  description: Template App React
  tags:
    - dotnet
    - csharp
    - webapi
  
  links:
    - url: https://github.com/hc-desa/app-test-react
      title: Repository
      icon: github

  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    # github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: hc-desa
  system: linux