
const getOne = () =>{

}

const getAll = () =>{
    return [
        {
            "id": "1",
            "mark": 'Mazda',
            "model": '3',
            "year": ' 2020 ',
            "version": "1.8 Gasolina",
            "cc": "1.8",
            "fuel": "Gasolina",
            "transmission":"Mecánica",
            "traction" : "FWD",
            "color": 'gris',
            "category": 'Sedán',
            "chasis": 'KS5434NLKN3453LK',
            "engine": 'KS5434NLKN3453LK',
            "patent": 'CCDL43',
            "description": '',
            "kilometres": '230.002',
            "status": "Finalizado",
            "dateIngress": "2012-05-06",
        },
        {
            "id": "2",
            "mark": 'Mazda',
            "model": '6',
            "year": 'Wed Jan 01 2018 00:00:00 GMT-0300 (hora de verano de Chile)',
            "version": "2.0 Gasolina",
            "cc": "2.0",
            "fuel": "Gasolina",
            "transmission":"Automatica",
            "traction" : "FWD",
            "color": 'Rojo metalico',
            "category": 'Sedán',
            "chasis": 'CNFDKJHCURENFJK2L3N2',
            "engine": 'CNFDKJHCURENFJK2L3N2',
            "patent": 'CXFSL43',
            "description": '',
            "kilometres": '30.002',
            "status": "Pago Pendiente",
            "dateIngress": "2021-07-05",

        },
        {
            "id": "3",
            "mark": 'Hyundai',
            "model": 'Sonata',
            "year": 'Wed Jan 01 1992 00:00:00 GMT-0300 (hora de verano de Chile)',
            "version": "1.5 Gasolina",
            "cc": "1.5",
            "fuel": "Gasolina",
            "transmission":"Mecanica",
            "traction" : "FWD",
            "color": 'Beige',
            "category": 'Sedán',
            "chasis": 'JBKJ23KJ42B34KJ2BK',
            "engine": 'JBKJ23KJ42B34KJ2BK',
            "patent": 'HBCU12',
            "description": '',
            "kilometres": '50.002',
            "status": "Pago Pendiente",
            "dateIngress": "2022-05-09",

        },
        {
            "id": "4",
            "mark": 'Chevrolet',
            "model": 'Tracker',
            "version": "1.8 Gasolina",
            "cc": "1.8",
            "fuel": "Gasolina",
            "transmission":"Automatica",
            "traction" : "FWD",
            "year": 'Wed Jan 01 2018 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Blanco',
            "category": 'Sedán',
            "chasis": 'KSLNN234LMN234LK2J',
            "engine": 'KSLNN234LMN234LK2J',
            "patent": 'HSCBG32',
            "description": '',
            "kilometres": '80.002',
            "status": "Finalizado",
            "dateIngress": "2022-10-03",

        },
        {
            "id": "5",
            "mark": 'Ford',
            "model": 'Ecosport',
            "version": "1.8 Gasolina",
            "cc": "1.8",
            "fuel": "Gasolina",
            "transmission":"Mecanica",
            "traction" : "FWD",
            "year": 'Wed Jan 01 2011 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Azul',
            "category": 'SUV',
            "chasis": 'SGDCHDSB3H2B43J3K4J',
            "engine": 'SGDCHDSB3H2B43J3K4J',
            "patent": 'KNJM21',
            "description": '',
            "kilometres": '130.002',
            "status": "Pago Pendiente",
            "dateIngress": "2022-07-26",

        },
        {
            "id": "6",
            "mark": 'Ford',
            "model": 'Explorer',
            "version": "3.2 Gasolina",
            "cc": "3.2",
            "fuel": "Gasolina",
            "transmission":"Mecanica",
            "traction" : "4WD",
            "year": 'Wed Jan 01 2018 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Rojo',
            "category": 'SUV',
            "chasis": 'KDNKJN45654KJ2N1K2JN',
            "engine": 'KDNKJN45654KJ2N1K2JN',
            "patent": 'MCBG12',
            "description": '',
            "kilometres": '20.002',
            "status": "Finalizado",
            "dateIngress": "2023-01-06",

        },
        {
            "id": "6",
            "mark": 'Jeep',
            "model": 'Grand Cherokee',
            "version": "2.7 Gasolina",
            "cc": "2.7",
            "fuel": "Gasolina",
            "transmission": "Automatica",
            "traction" : "4x4",
            "year": 'Wed Jan 01 2022 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Blanco',
            "category": 'SUV',
            "chasis": 'KNUK2J3N42MNK42J3N4',
            "engine": 'KNUK2J3N42MNK42J3N4',
            "patent": 'XLSN23',
            "description": '',
            "kilometres": '6.002',
            "status": "Pago Pendiente",
            "dateIngress": "2022-09-30",

        },
        {
            "id": "7",
            "mark": 'Chevrolet',
            "model": 'Captiva',
            "version": "1.8 Gasolina",
            "cc": "1.8",
            "fuel": "Gasolina",
            "transmission":"Mecanica",
            "traction" : "FWD",
            "year": 'Wed Jan 01 2012 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Gris',
            "category": 'SUV',
            "chasis": 'MKASDMNAL2342L4N4LK',
            "engine": 'MKASDMNAL2342L4N4LK',
            "patent": 'MSCHG43',
            "description": '',
            "kilometres": '140.002',
            "status": "Ingresado",
            "dateIngress": "2022-08-05",

        },
        {
            "id": "8",
            "mark": 'Hyundai',
            "model": 'Grand SantaFe',
            "version": "2.2 Diésel",
            "cc": "2.2",
            "fuel": "Diésel",
            "transmission": "Automatica",
            "traction" : "4WD",
            "year": 'Wed Jan 01 2015 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Azul',
            "category": 'Sedán',
            "chasis": 'KS5434NLKN3453LK',
            "engine": 'KS5434NLKN3453LK',
            "patent": 'CCDL43',
            "description": '',
            "kilometres": '280.002',
            "status": "Ingresado",
            "dateIngress": "2022-06-06"
        },
        {
            "id": "9",
            "mark": 'Kia',
            "model": 'Sportage',
            "version": "2.0 Gasolina",
            "cc": "2.0",
            "fuel": "Gasolina",
            "transmission":"Mecanica",
            "traction" : "4WD",
            "year": 'Wed Jan 01 2012 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Rojo',
            "category": 'SUV',
            "chasis": 'LKSJ3N24NKJN34K2LN',
            "engine": 'LKSJ3N24NKJN34K2LN',
            "patent": 'SDAD32',
            "description": '',
            "kilometres": '40.002',
            "status": "Pago Pendiente",
            "dateIngress": "2023-01-11",
        },
        {
            "id": "10",
            "mark": 'Kia',
            "model": 'Sorento',
            "version": "2.0 Diésel",
            "cc": "2.0",
            "fuel": "Diésel",
            "transmission":"Automatica",
            "traction" : "4WD",
            "year": 'Wed Jan 01 2017 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Rojo',
            "category": 'SUV',
            "chasis": 'LSNDJFNKJN232L3NL',
            "engine": 'LSNDJFNKJN232L3NL',
            "patent": 'NSDK65',
            "description": '',
            "kilometres": '34.002',
            "status": "Finalizado",
            "dateIngress": "2022-03-12",

        },
        {
            "id": "10",
            "mark": 'Toyota',
            "model": 'Fortunner',
            "version": "2.5 Diesel",
            "cc": "2.5",
            "fuel": "Diesel",
            "transmission":"Automatica",
            "traction" : "4x4",
            "year": 'Wed Jan 01 2017 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Gris',
            "category": 'SUV',
            "chasis": 'KSD3KL345LK345N3L4',
            "engine": 'KSD3KL345LK345N3L4',
            "patent": 'LMNS22',
            "description": '',
            "kilometres": '54.002',
            "status": "Retiro Pendiente",
            "dateIngress": "2022-12-22",

        },
        {
            "id": "10",
            "mark": 'Toyota',
            "model": 'Rav 4',
            "version": "2.5 Diesel",
            "cc": "2.5",
            "fuel": "Diesel",
            "transmission":"Automatica",
            "traction" : "FWD",
            "year": 'Wed Jan 01 2018 00:00:00 GMT-0300 (hora de verano de Chile)',
            "color": 'Rojo',
            "category": 'SUV',
            "chasis": 'KSKDFS3242MKOIMI32',
            "engine": 'KSKDFS3242MKOIMI32',
            "patent": 'LMKD22',
            "description": '',
            "kilometres": '54.002',
            "status": "Retiro Pendiente",
            "dateIngress": "2023-01-06",

        }
   
    ];
}

const save = () =>{

}

const update = () =>{

}

export {getOne,getAll,save,update};
